FROM internetsystemsconsortium/bind9:9.16
RUN rndc-confgen > /etc/bind/rndc.key
# COPY db.myorg.net /etc/bind/db.myorg.net
# COPY named.conf.local /etc/bind/named.conf.local
# COPY named.conf.options /etc/bind/named.conf.options
